/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.chiriboga.views;

import javax.swing.JOptionPane;
import com.chiriboga.business.BaseAlgorithms;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.text.BadLocationException;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import org.knowm.xchart.BitmapEncoder;
import org.knowm.xchart.XYChart;
import org.knowm.xchart.XYChartBuilder;



/**
 *
 * @author alex
 */
public class PerformanceView extends javax.swing.JFrame {
     
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PerformanceView.class.getName());

    /**
     * Creates new form PerformanceView
     */
    public PerformanceView() {
        initComponents();
        initAppComponents();
    }
    
    public void initAppComponents(){
        this.setLocationRelativeTo(null);
        baseAlgorithms = new BaseAlgorithms();
        this.consoleArea.setBackground(Color.BLACK);
        this.codeEditorPanel.setEditable(false);
        
        //Local Variables
        this.xData = new ArrayList<>();
        this.yData = new ArrayList<>();
        
        //
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        simpleLoopAlgBtn = new javax.swing.JButton();
        algeSumAlg = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        doubleLoopAlg = new javax.swing.JButton();
        showPairsAlg = new javax.swing.JButton();
        countHalvesAlgBtn = new javax.swing.JButton();
        showImformationBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        sizeInputLabel = new javax.swing.JSpinner();
        resetList = new javax.swing.JButton();
        graphPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        codeEditorPanel = new javax.swing.JEditorPane();
        jLabel4 = new javax.swing.JLabel();
        consolePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        consoleArea = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medidor de rendimiento 🔥");
        setName("performanceWindow"); // NOI18N

        optionsPanel.setBackground(new java.awt.Color(204, 204, 204));
        optionsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        optionsPanel.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Medidor de Rendimiento");

        simpleLoopAlgBtn.setBackground(new java.awt.Color(102, 102, 255));
        simpleLoopAlgBtn.setForeground(new java.awt.Color(255, 255, 255));
        simpleLoopAlgBtn.setText("Bucle simple");
        simpleLoopAlgBtn.setBorder(null);
        simpleLoopAlgBtn.setBorderPainted(false);
        simpleLoopAlgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpleLoopAlgBtnActionPerformed(evt);
            }
        });

        algeSumAlg.setBackground(new java.awt.Color(102, 102, 255));
        algeSumAlg.setForeground(new java.awt.Color(255, 255, 255));
        algeSumAlg.setText("Suma algebraíca");
        algeSumAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algeSumAlgActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingresa el número de elementos");

        doubleLoopAlg.setBackground(new java.awt.Color(102, 102, 255));
        doubleLoopAlg.setForeground(new java.awt.Color(255, 255, 255));
        doubleLoopAlg.setText("Bucle doble");
        doubleLoopAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleLoopAlgActionPerformed(evt);
            }
        });

        showPairsAlg.setBackground(new java.awt.Color(102, 102, 255));
        showPairsAlg.setForeground(new java.awt.Color(255, 255, 255));
        showPairsAlg.setText("Mostrar pares");
        showPairsAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPairsAlgActionPerformed(evt);
            }
        });

        countHalvesAlgBtn.setBackground(new java.awt.Color(102, 102, 255));
        countHalvesAlgBtn.setForeground(new java.awt.Color(255, 255, 255));
        countHalvesAlgBtn.setText("Cuenta mitades");
        countHalvesAlgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countHalvesAlgBtnActionPerformed(evt);
            }
        });

        showImformationBtn.setBackground(new java.awt.Color(255, 153, 0));
        showImformationBtn.setForeground(new java.awt.Color(255, 255, 255));
        showImformationBtn.setText("Información");
        showImformationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showImformationBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Elaborado por: Alexander Chiriboga");

        sizeInputLabel.setModel(new javax.swing.SpinnerNumberModel(0L, null, null, 100L));

        resetList.setBackground(new java.awt.Color(255, 51, 51));
        resetList.setForeground(new java.awt.Color(255, 255, 255));
        resetList.setText("Reset");
        resetList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsPanelLayout.createSequentialGroup()
                        .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(countHalvesAlgBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(showPairsAlg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(doubleLoopAlg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(algeSumAlg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(simpleLoopAlgBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sizeInputLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(59, 59, 59))))
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(showImformationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resetList, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sizeInputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(simpleLoopAlgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(algeSumAlg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(doubleLoopAlg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(showPairsAlg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(countHalvesAlgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showImformationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetList, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(codeEditorPanel);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Código fuente");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jScrollPane2.setViewportView(consoleArea);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setText("Consola");

        javax.swing.GroupLayout consolePanelLayout = new javax.swing.GroupLayout(consolePanel);
        consolePanel.setLayout(consolePanelLayout);
        consolePanelLayout.setHorizontalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consolePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(consolePanelLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel5)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        consolePanelLayout.setVerticalGroup(
            consolePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consolePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(consolePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(consolePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpleLoopAlgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpleLoopAlgBtnActionPerformed

        try {
            long startTime = System.currentTimeMillis();
            long inputSize = this.readFromInputSize();
            long total = this.baseAlgorithms.totalSumLoopAlg(inputSize);
            this.writeOnConsole("El total es: " + total);
            long endTime = System.currentTimeMillis();
            long avgTime = endTime - startTime;
            this.writeOnConsole("El tiempo en milisegundos segundos es: " + avgTime);
            this.codeEditorPanel.setText(this.baseAlgorithms.getTotalSumLoopAlg());
            this.sizeInputLabel.setValue(0);
            xData.add(inputSize);
            yData.add(avgTime);
            this.generate2DGraph(xData, yData);
        }catch(Exception ex) {
            System.out.println("El resultado es: " + ex.getMessage());
        }
    }//GEN-LAST:event_simpleLoopAlgBtnActionPerformed

    private void algeSumAlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algeSumAlgActionPerformed
        try{
            long startTime = System.currentTimeMillis();
            long inputSize = this.readFromInputSize();
            long total = this.baseAlgorithms.algebraicSumAlg(inputSize);
            long endTime = System.currentTimeMillis();
            String result = "El resultado algebraico es: " + total;
            this.codeEditorPanel.setText(this.baseAlgorithms.getTotalSumAlgebraicAlg());
            this.writeOnConsole( result );
            long avgTime = endTime - startTime;
            xData.add(inputSize);
            yData.add(avgTime);
            this.generate2DGraph(xData, yData);
            this.sizeInputLabel.setValue(0);
        }catch(Exception exception) {
            throw exception;
        }
                
    }//GEN-LAST:event_algeSumAlgActionPerformed

    private void doubleLoopAlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleLoopAlgActionPerformed
        
        long inputSize = this.readFromInputSize();
        long startTime = System.currentTimeMillis();
        String result = this.baseAlgorithms.CountBottomToTop(inputSize);
        this.codeEditorPanel.setText(this.baseAlgorithms.getDoubleLoopAlg());
        this.writeOnConsole(result);
        long endTime = System.currentTimeMillis();
        long avgTime = endTime - startTime;
        xData.add(inputSize);
        yData.add(avgTime);
        this.generate2DGraph(xData, yData);
        this.sizeInputLabel.setValue(0);
    }//GEN-LAST:event_doubleLoopAlgActionPerformed

    private void showPairsAlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPairsAlgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showPairsAlgActionPerformed

    private void countHalvesAlgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countHalvesAlgBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countHalvesAlgBtnActionPerformed

    private void showImformationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showImformationBtnActionPerformed

        String appInformation = "Esta aplicación fue desarrollada con el objetivo de ilustrar la complejidad temporal y espacial de los algoritmos.\n" +
        "Se inspira en la demostración presentada por Rithm School, adaptada y extendida para mis fines educativos.";
        JOptionPane.showMessageDialog(null, appInformation);
    }//GEN-LAST:event_showImformationBtnActionPerformed

    private void resetListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetListActionPerformed
        this.xData.clear();
        this.yData.clear();
        this.codeEditorPanel.setText("");
        this.chart.getSeriesMap().clear();
    }//GEN-LAST:event_resetListActionPerformed

    private long readFromInputSize() {
        try{
            long inputSize = ((Number) this.sizeInputLabel.getValue()).longValue();
            return inputSize;
        }catch(Exception ex){
            this.writeOnConsole(ex.getMessage());
            System.out.println("Ha fallado");
            return 0;
        }
    }
    
    private void writeOnConsole(String text){
        StyledDocument doc = this.consoleArea.getStyledDocument();
        var myStyle =  this.consoleArea.addStyle("miEstilo", null);
        StyleConstants.setForeground(myStyle, Color.GREEN);
        try{
            doc.insertString(doc.getLength(), text, myStyle);
            doc.insertString(doc.getLength(), "\n", myStyle);
        }catch (BadLocationException e) {
            e.printStackTrace();
        }
    }
    
    private void generate2DGraph(List<Long> xData, List<Long> yData){        
        this.chart = new XYChartBuilder()
                .title("Análisis de rendimiento (Tiempo-Tamaño)")
                .height(350)
                .width(650)
                .xAxisTitle("Cantidad de elementos")
                .yAxisTitle("Tiempo de ejecución")
                .build();
        this.chart.addSeries("Algoritmo A", xData, yData);
        
        //Crea una imagen que agrega a un label para poder graficar
         BufferedImage image = BitmapEncoder.getBufferedImage(this.chart);
         JLabel label = new JLabel(new ImageIcon(image));
         
         this.graphPanel.removeAll();
         this.graphPanel.setLayout(new BorderLayout());
         this.graphPanel.add(label, BorderLayout.CENTER);
         this.graphPanel.revalidate();
         this.graphPanel.repaint();         
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PerformanceView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton algeSumAlg;
    private javax.swing.JEditorPane codeEditorPanel;
    private javax.swing.JTextPane consoleArea;
    private javax.swing.JPanel consolePanel;
    private javax.swing.JButton countHalvesAlgBtn;
    private javax.swing.JButton doubleLoopAlg;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JButton resetList;
    private javax.swing.JButton showImformationBtn;
    private javax.swing.JButton showPairsAlg;
    private javax.swing.JButton simpleLoopAlgBtn;
    private javax.swing.JSpinner sizeInputLabel;
    // End of variables declaration//GEN-END:variables

    //My variables declarations
    
    private com.chiriboga.business.BaseAlgorithms baseAlgorithms;
    private List<Long> xData;
    private List<Long> yData;
    private XYChart chart;
}
